// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3oUowO2aC-5cWSc2Bai08gsCJH8kmNUU',
    appId: '1:256034913398:web:89227d0d083908b1fa3357',
    messagingSenderId: '256034913398',
    projectId: 'testauth-e3f34',
    authDomain: 'testauth-e3f34.firebaseapp.com',
    storageBucket: 'testauth-e3f34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvQXCg1xoBtDzOERI4f5aqyde_O8IkllU',
    appId: '1:256034913398:android:4610510fd8569b1bfa3357',
    messagingSenderId: '256034913398',
    projectId: 'testauth-e3f34',
    storageBucket: 'testauth-e3f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjguVtRiGOdky_Jh2mwNR6mMfKvr7vnn8',
    appId: '1:256034913398:ios:03bfd9ab2251c0c1fa3357',
    messagingSenderId: '256034913398',
    projectId: 'testauth-e3f34',
    storageBucket: 'testauth-e3f34.appspot.com',
    iosClientId: '256034913398-ksblnv8ru56arl03e2ekr8nt7m675s33.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjguVtRiGOdky_Jh2mwNR6mMfKvr7vnn8',
    appId: '1:256034913398:ios:03bfd9ab2251c0c1fa3357',
    messagingSenderId: '256034913398',
    projectId: 'testauth-e3f34',
    storageBucket: 'testauth-e3f34.appspot.com',
    iosClientId: '256034913398-ksblnv8ru56arl03e2ekr8nt7m675s33.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
